sub: #远程Clash配置文件，注有#的是失效的链接
  - http://94.23.116.185:7794/clash/proxies
  - http://101.132.255.205:1234/clash/proxies
  - https://pc.adlionvm.tk/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://proxypool.laowang.me/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
  - https://us-proxypool.herokuapp.com/clash/proxies
  - https://eu-proxypool.herokuapp.com/clash/proxies
local: ["into.yaml","../../Clash.yaml"] #同级、上级或下级目录的本地Clash配置文件，上级目录的文件需要使用"../"进行引导
